package bcc.springhibernate.model;
// Generated Jan 10, 2018 6:48:04 PM by Hibernate Tools 5.1.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chamsoc generated by hbm2java
 */
@Entity
@Table(name = "chamsoc", catalog = "hotrobanhang")
public class Chamsoc implements java.io.Serializable {

	private Integer id;
	private Khachhang khachhang;
	private Integer nhanvienchamsoc;
	private Integer nhanvienbanhang;
	private Integer nhanviengiaohang;
	private Date ngay;
	private Integer lan;
	private String noidung;
	private Date ngaycstiep;
	private String ghichu;
	private Integer hoadonId;
	private String trangthai;
	private Set<Chitietchamsoc> chitietchamsocs = new HashSet<Chitietchamsoc>(0);
	private Set<Chitietchamsoc> chitietchamsocs_1 = new HashSet<Chitietchamsoc>(0);

	public Chamsoc() {
	}

	public Chamsoc(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	public Chamsoc(Khachhang khachhang, Integer nhanvienchamsoc, Integer nhanvienbanhang, Integer nhanviengiaohang,
			Date ngay, Integer lan, String noidung, Date ngaycstiep, String ghichu, Integer hoadonId, String trangthai,
			Set<Chitietchamsoc> chitietchamsocs, Set<Chitietchamsoc> chitietchamsocs_1) {
		this.khachhang = khachhang;
		this.nhanvienchamsoc = nhanvienchamsoc;
		this.nhanvienbanhang = nhanvienbanhang;
		this.nhanviengiaohang = nhanviengiaohang;
		this.ngay = ngay;
		this.lan = lan;
		this.noidung = noidung;
		this.ngaycstiep = ngaycstiep;
		this.ghichu = ghichu;
		this.hoadonId = hoadonId;
		this.trangthai = trangthai;
		this.chitietchamsocs = chitietchamsocs;
		this.chitietchamsocs_1 = chitietchamsocs_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "khachhang_id", nullable = false)
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@Column(name = "nhanvienchamsoc")
	public Integer getNhanvienchamsoc() {
		return this.nhanvienchamsoc;
	}

	public void setNhanvienchamsoc(Integer nhanvienchamsoc) {
		this.nhanvienchamsoc = nhanvienchamsoc;
	}

	@Column(name = "nhanvienbanhang")
	public Integer getNhanvienbanhang() {
		return this.nhanvienbanhang;
	}

	public void setNhanvienbanhang(Integer nhanvienbanhang) {
		this.nhanvienbanhang = nhanvienbanhang;
	}

	@Column(name = "nhanviengiaohang")
	public Integer getNhanviengiaohang() {
		return this.nhanviengiaohang;
	}

	public void setNhanviengiaohang(Integer nhanviengiaohang) {
		this.nhanviengiaohang = nhanviengiaohang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay", length = 19)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Column(name = "lan")
	public Integer getLan() {
		return this.lan;
	}

	public void setLan(Integer lan) {
		this.lan = lan;
	}

	@Column(name = "noidung")
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaycstiep", length = 19)
	public Date getNgaycstiep() {
		return this.ngaycstiep;
	}

	public void setNgaycstiep(Date ngaycstiep) {
		this.ngaycstiep = ngaycstiep;
	}

	@Column(name = "ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "hoadon_id")
	public Integer getHoadonId() {
		return this.hoadonId;
	}

	public void setHoadonId(Integer hoadonId) {
		this.hoadonId = hoadonId;
	}

	@Column(name = "trangthai", length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chamsoc")
	public Set<Chitietchamsoc> getChitietchamsocs() {
		return this.chitietchamsocs;
	}

	public void setChitietchamsocs(Set<Chitietchamsoc> chitietchamsocs) {
		this.chitietchamsocs = chitietchamsocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chamsoc")
	public Set<Chitietchamsoc> getChitietchamsocs_1() {
		return this.chitietchamsocs_1;
	}

	public void setChitietchamsocs_1(Set<Chitietchamsoc> chitietchamsocs_1) {
		this.chitietchamsocs_1 = chitietchamsocs_1;
	}

}
