package bcc.springhibernate.model;
// Generated Jan 13, 2018 1:49:35 PM by Hibernate Tools 5.1.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiethoadon generated by hbm2java
 */
@Entity
@Table(name = "chitiethoadon", catalog = "hotrobanhang")
public class Chitiethoadon implements java.io.Serializable {

	private Integer id;
	private Hanghoa hanghoa;
	private Hoadon hoadon;
	private Long dongia;
	private Integer soluong;
	private Long giaban;
	private Long thanhtien;
	private String trangthai;
	private String ghichu;

	public Chitiethoadon() {
	}

	public Chitiethoadon(Hanghoa hanghoa, Hoadon hoadon) {
		this.hanghoa = hanghoa;
		this.hoadon = hoadon;
	}

	public Chitiethoadon(Hanghoa hanghoa, Hoadon hoadon, Long dongia, Integer soluong, Long giaban, Long thanhtien,
			String trangthai, String ghichu) {
		this.hanghoa = hanghoa;
		this.hoadon = hoadon;
		this.dongia = dongia;
		this.soluong = soluong;
		this.giaban = giaban;
		this.thanhtien = thanhtien;
		this.trangthai = trangthai;
		this.ghichu = ghichu;
	}

	public Chitiethoadon(Integer id, Hanghoa hanghoa, Hoadon hoadon, Long dongia, Integer soluong, Long giaban,
			Long thanhtien, String trangthai, String ghichu) {
		super();
		this.id = id;
		this.hanghoa = hanghoa;
		this.hoadon = hoadon;
		this.dongia = dongia;
		this.soluong = soluong;
		this.giaban = giaban;
		this.thanhtien = thanhtien;
		this.trangthai = trangthai;
		this.ghichu = ghichu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idhanghoa", nullable = false)
	public Hanghoa getHanghoa() {
		return this.hanghoa;
	}

	public void setHanghoa(Hanghoa hanghoa) {
		this.hanghoa = hanghoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idhoadon", nullable = false)
	public Hoadon getHoadon() {
		return this.hoadon;
	}

	public void setHoadon(Hoadon hoadon) {
		this.hoadon = hoadon;
	}

	@Column(name = "dongia", precision = 10, scale = 0)
	public Long getDongia() {
		return this.dongia;
	}

	public void setDongia(Long dongia) {
		this.dongia = dongia;
	}

	@Column(name = "soluong")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@Column(name = "giaban", precision = 10, scale = 0)
	public Long getGiaban() {
		return this.giaban;
	}

	public void setGiaban(Long giaban) {
		this.giaban = giaban;
	}

	@Column(name = "thanhtien", precision = 10, scale = 0)
	public Long getThanhtien() {
		return this.thanhtien;
	}

	public void setThanhtien(Long thanhtien) {
		this.thanhtien = thanhtien;
	}

	@Column(name = "trangthai", length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "ghichu", length = 95)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
