package bcc.springhibernate.model;
// Generated Jan 5, 2018 7:55:13 PM by Hibernate Tools 5.1.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietchamsoc generated by hbm2java
 */
@Entity
@Table(name = "chitietchamsoc", catalog = "hotrobanhang")
public class Chitietchamsoc implements java.io.Serializable {

	private Integer id;
	private Chamsoc chamsoc;
	private Tieuchichamsoc tieuchichamsoc;
	private Integer diem;
	private String trangthai;
	private String mota;

	public Chitietchamsoc() {
	}

	public Chitietchamsoc(Chamsoc chamsoc, Tieuchichamsoc tieuchichamsoc, Integer diem, String trangthai, String mota) {
		this.chamsoc = chamsoc;
		this.tieuchichamsoc = tieuchichamsoc;
		this.diem = diem;
		this.trangthai = trangthai;
		this.mota = mota;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idchamsoc")
	public Chamsoc getChamsoc() {
		return this.chamsoc;
	}

	public void setChamsoc(Chamsoc chamsoc) {
		this.chamsoc = chamsoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tieuchichamsoc")
	public Tieuchichamsoc getTieuchichamsoc() {
		return this.tieuchichamsoc;
	}

	public void setTieuchichamsoc(Tieuchichamsoc tieuchichamsoc) {
		this.tieuchichamsoc = tieuchichamsoc;
	}

	@Column(name = "diem")
	public Integer getDiem() {
		return this.diem;
	}

	public void setDiem(Integer diem) {
		this.diem = diem;
	}

	@Column(name = "trangthai", length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "mota")
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

}
