package bcc.springhibernate.model;
// Generated Jan 13, 2018 1:49:35 PM by Hibernate Tools 5.1.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kpi generated by hbm2java
 */
@Entity
@Table(name = "kpi", catalog = "hotrobanhang")
public class Kpi implements java.io.Serializable {

	private Integer id;
	private String ten;
	private Integer so;
	private Double phantram;
	private String trangthai;
	private String mota;
	private Set<Nhanvienkpi> nhanvienkpis = new HashSet<Nhanvienkpi>(0);
	private Set<Nhanvienkpi> nhanvienkpis_1 = new HashSet<Nhanvienkpi>(0);

	public Kpi() {
	}

	public Kpi(String ten, Integer so, Double phantram, String trangthai, String mota, Set<Nhanvienkpi> nhanvienkpis,
			Set<Nhanvienkpi> nhanvienkpis_1) {
		this.ten = ten;
		this.so = so;
		this.phantram = phantram;
		this.trangthai = trangthai;
		this.mota = mota;
		this.nhanvienkpis = nhanvienkpis;
		this.nhanvienkpis_1 = nhanvienkpis_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ten", length = 45)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "so")
	public Integer getSo() {
		return this.so;
	}

	public void setSo(Integer so) {
		this.so = so;
	}

	@Column(name = "phantram", precision = 22, scale = 0)
	public Double getPhantram() {
		return this.phantram;
	}

	public void setPhantram(Double phantram) {
		this.phantram = phantram;
	}

	@Column(name = "trangthai", length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "mota")
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpi")
	public Set<Nhanvienkpi> getNhanvienkpis() {
		return this.nhanvienkpis;
	}

	public void setNhanvienkpis(Set<Nhanvienkpi> nhanvienkpis) {
		this.nhanvienkpis = nhanvienkpis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpi")
	public Set<Nhanvienkpi> getNhanvienkpis_1() {
		return this.nhanvienkpis_1;
	}

	public void setNhanvienkpis_1(Set<Nhanvienkpi> nhanvienkpis_1) {
		this.nhanvienkpis_1 = nhanvienkpis_1;
	}

}
