package bcc.springhibernate.model;
// Generated Jan 20, 2018 8:57:07 AM by Hibernate Tools 5.1.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhanvienkpi generated by hbm2java
 */
@Entity
@Table(name = "nhanvienkpi", catalog = "hotrobanhang")
public class Nhanvienkpi implements java.io.Serializable {
	private Integer id;
	private Kpi kpi;
	private Nhanvien nhanvien;
	private Long chitieudangky;
	private Date ngaydangky;
	private Date ngayhoanthanh;
	private String trangthai;
	private String mota;

	public Nhanvienkpi() {
	}

	public Nhanvienkpi(Kpi kpi, Nhanvien nhanvien, Long chitieudangky, Date ngaydangky, Date ngayhoanthanh, String trangthai, String mota) {
		this.kpi = kpi;
		this.nhanvien = nhanvien;
		this.chitieudangky = chitieudangky;
		this.ngaydangky = ngaydangky;
		this.ngayhoanthanh = ngayhoanthanh;
		this.trangthai = trangthai;
		this.mota = mota;
	}

	@Id @GeneratedValue(strategy=IDENTITY)


	@Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="kpi")
	public Kpi getKpi() {
		return this.kpi;
	}

	public void setKpi(Kpi kpi) {
		this.kpi = kpi;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="nhanvien")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}


	@Column(name="chitieudangky", precision=10, scale=0)
	public Long getChitieudangky() {
		return this.chitieudangky;
	}

	public void setChitieudangky(Long chitieudangky) {
		this.chitieudangky = chitieudangky;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="ngaydangky", length=19)
	public Date getNgaydangky() {
		return this.ngaydangky;
	}

	public void setNgaydangky(Date ngaydangky) {
		this.ngaydangky = ngaydangky;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="ngayhoanthanh", length=19)
	public Date getNgayhoanthanh() {
		return this.ngayhoanthanh;
	}

	public void setNgayhoanthanh(Date ngayhoanthanh) {
		this.ngayhoanthanh = ngayhoanthanh;
	}


	@Column(name="trangthai", length=45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}


	@Column(name="mota")
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}


}
