package bcc.springhibernate.model;
// Generated Jan 20, 2018 8:57:07 AM by Hibernate Tools 5.1.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Quyen generated by hbm2java
 */
@Entity
@Table(name = "quyen", catalog = "hotrobanhang", uniqueConstraints = @UniqueConstraint(columnNames = "maquyen"))
public class Quyen implements java.io.Serializable {

	private Integer id;
	private String maquyen;
	private String tenquyen;
	private String mota;
	private String trangthai;
	private Set<Taikhoan> taikhoans = new HashSet<Taikhoan>(0);
	private Set<Taikhoan> taikhoans_1 = new HashSet<Taikhoan>(0);

	public Quyen() {
	}

	public Quyen(String maquyen) {
		this.maquyen = maquyen;
	}

	public Quyen(String maquyen, String tenquyen, String mota, String trangthai, Set<Taikhoan> taikhoans,
			Set<Taikhoan> taikhoans_1) {
		this.maquyen = maquyen;
		this.tenquyen = tenquyen;
		this.mota = mota;
		this.trangthai = trangthai;
		this.taikhoans = taikhoans;
		this.taikhoans_1 = taikhoans_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "maquyen", unique = true, nullable = false, length = 45)
	public String getMaquyen() {
		return this.maquyen;
	}

	public void setMaquyen(String maquyen) {
		this.maquyen = maquyen;
	}

	@Column(name = "tenquyen", length = 45)
	public String getTenquyen() {
		return this.tenquyen;
	}

	public void setTenquyen(String tenquyen) {
		this.tenquyen = tenquyen;
	}

	@Column(name = "mota", length = 45)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "trangthai", length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "taikhoan_quyen", catalog = "hotrobanhang", joinColumns = {
			@JoinColumn(name = "quyen_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "taikhoan_id", nullable = false, updatable = false) })
	public Set<Taikhoan> getTaikhoans() {
		return this.taikhoans;
	}

	public void setTaikhoans(Set<Taikhoan> taikhoans) {
		this.taikhoans = taikhoans;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "taikhoan_quyen", catalog = "hotrobanhang", joinColumns = {
			@JoinColumn(name = "quyen_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "taikhoan_id", nullable = false, updatable = false) })
	public Set<Taikhoan> getTaikhoans_1() {
		return this.taikhoans_1;
	}

	public void setTaikhoans_1(Set<Taikhoan> taikhoans_1) {
		this.taikhoans_1 = taikhoans_1;
	}

}
