package bcc.springhibernate.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ungluong generated by hbm2java
 */
@Entity
@Table(name="ungluong"
        ,catalog="hotrobanhang"
)
public class Ungluong  implements java.io.Serializable {


    private Integer id;
    private Luong luong;
    private Long sotienung;
    private Date ngayung;
    private String noidung;
    private String trangthai;
    private String ghichu;

    public Ungluong() {
    }


    public Ungluong(Luong luong) {
        this.luong = luong;
    }

    public Ungluong(Luong luong, Long sotienung, Date ngayung, String noidung,String trangthai, String ghichu) {
        this.luong = luong;
        this.sotienung = sotienung;
        this.ngayung = ngayung;
        this.noidung = noidung;
        this.trangthai = trangthai;
        this.ghichu = ghichu;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idluong", nullable = false)
    public Luong getLuong() {
        return this.luong;
    }

    public void setLuong(Luong luong) {
        this.luong = luong;
    }


    @Column(name = "sotienung", precision = 10, scale = 0)
    public Long getSotienung() {
        return this.sotienung;
    }

    public void setSotienung(Long sotienung) {
        this.sotienung = sotienung;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ngayung", length = 19)
    public Date getNgayung() {
        return this.ngayung;
    }

    public void setNgayung(Date ngayung) {
        this.ngayung = ngayung;
    }


    @Column(name = "noidung", length = 65535)
    public String getNoidung() {
        return this.noidung;
    }

    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }
    @Column(name = "trangthai", length = 45)
    public String getTrangthai() {
        return this.trangthai;
    }

    public void setTrangthai(String trangthai) {
        this.trangthai = trangthai;
    }

    @Column(name = "ghichu")
    public String getGhichu() {
        return this.ghichu;
    }

    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
}

